### ISSUE TITLE
Access Training Reports | Mobile (do after #182 implemented)

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#143] opened 2023-04-25 19:46 UTC
As an A/OPC, I want to access training reports from mobile device, so that I can do this without using a laptop.

Acceptance criteria:

- [ ] A/OPCs are able to access training reports from a mobile device
  - Note: this story is intended to capture design tweaks, if any, that might be needed for the "access training reports" flow on mobile

**Comment by klohman** [comment] 2023-07-24 17:58
@JessicaMarine1 I tested the generate report flow on mobile and did not see any issues. Unless there was something specific this issue was intended to fix, I think we can close it.

**Closed** 2023-07-24 19:08 UTC
Labels: Reports, Design Needed, Good issue for ATO code freeze
